### ISSUE TITLE
Need location for tools docs

### ISSUE THREAD

**Issue by emplums** [primer/blueprints#15]
Atom packages, docset, GH local environment, and linting don't map well to our new setup. In the new header, they are nested under a Tools section, but they live in primer.style/css. Should we have a Tools site that hosts the docs for all of these?

**Comment by broccolini** [comment]
I think for now it can point to Primer CSS and we move Tools into the left nav. But yeah I was thinking we may want to make a tools site, or section of primer.style in future.
