### ISSUE TITLE
Add padding to CodeExample

### ISSUE THREAD

**Issue by emplums** [primer/blueprints#36]
### Problem

Code examples that have outlines or box-shadows get cut of on the edges:

![Screen Shot 2019-05-22 at 8 31 44 AM](https://user-images.githubusercontent.com/378023/58137300-bb2b4c80-7c6c-11e9-8b98-a0920e103139.png)

### Possible solution

Instead of adding the "default padding" to the parent of the `<iframe>`, move the padding inside the `<iframe>`.

![Screen Shot 2019-05-22 at 8 47 54 AM](https://user-images.githubusercontent.com/378023/58137749-62f54a00-7c6e-11e9-9329-203660fb63cb.png)

![image](https://user-images.githubusercontent.com/378023/58137763-6dafdf00-7c6e-11e9-9bbb-228d04708cea.png)

**Comment by simurai** [comment]
Another cool thing and I remember chatting with @shawnbot about it. Being able to "pass in" any class or maybe even inline styles through the code fence declaration.

```
  ```html class="text-center" style="min-height: 100px;"
  <details>
```

Would output:

```
<iframe>
  ...
  <div class="p3 text-center" style="min-height: 100px;">
    <details>
```

This would allow us to hide the "setup" styles from code examples. And avoid being copy&pasted by mistake.

**Comment by emplums** [comment]
@simurai can you remind me where you saw this bug popping up again?

**Comment by simurai** [comment]
On the [Primer CSS buttons](https://primer.style/css/components/buttons) page, after clicking on a button, the "blue focus" outline should be visible:

Actual | Expected
--- | ---
![Screen Shot 2019-06-03 at 10 38 39 AM](https://user-images.githubusercontent.com/378023/58770809-012ccc80-85ec-11e9-94a9-b3c33c8f1e34.png) | ![Screen Shot 2019-06-03 at 10 40 03 AM](https://user-images.githubusercontent.com/378023/58770810-012ccc80-85ec-11e9-8109-a327cc078f8a.png)

Another example is the `Label--outline` on the [Primer CSS labels](https://primer.style/css/components/labels) page. They seem to have a negative top/bottom margin:

![image](https://user-images.githubusercontent.com/378023/58770899-739dac80-85ec-11e9-9f0d-f502e0353e8a.png)

Which hides the top/bottom border when in an iframe.

Actual | Expected
--- | ---
![Screen Shot 2019-06-03 at 10 44 58 AM](https://user-images.githubusercontent.com/378023/58770988-dee77e80-85ec-11e9-9ce0-91a9711257de.png) | ![Screen Shot 2019-06-03 at 10 45 44 AM](https://user-images.githubusercontent.com/378023/58770989-df801500-85ec-11e9-9b00-9cc25404d55f.png)
